---
zabbixServer:
  replicaCount: 1
  image:
    repository: gcr.io/bitninjaio/zabbix
    tag: 5.4-server
    pullPolicy: "Always" # "IfNotPresent"
    pullSecrets: [ "name": "bitninjaio-at-gmail-dot-com" ]
  DB_SERVER_HOST: "zabbix-postgresql"
  POSTGRES_USER: "zabbix"
  POSTGRES_PASSWORD: "zabbix_db_pwd"
  POSTGRES_DB: "zabbix"

zabbixPostgresql:
  image:
    repository: gcr.io/bitninjaio/postgresql
    tag: 13.1
    pullPolicy: "Always" # "IfNotPresent"
    pullSecrets: [ "name": "bitninjaio-at-gmail-dot-com" ]
  storage:
    size: 32Gi
  POSTGRES_USER: "zabbix"
  POSTGRES_PASSWORD: "zabbix_db_pwd"
  POSTGRESQL_MAX_CONNECTIONS: 250

zabbixWeb:
  replicaCount: 2
  image:
    repository: gcr.io/bitninjaio/zabbix
    tag: 5.4-web
    pullPolicy: "Always" # "IfNotPresent"
    pullSecrets: [ "name": "bitninjaio-at-gmail-dot-com" ]
  ZBX_SERVER_HOST: "zabbix-server"
  ZBX_SERVER_PORT: 10051
  ZBX_SERVER_NAME: "zabbix"
  DB_SERVER_HOST: "zabbix-postgresql"
  DB_SERVER_PORT: 5432
  POSTGRES_USER: "zabbix"
  POSTGRES_PASSWORD: "zabbix_db_pwd"
  POSTGRES_DB: "zabbix"

zabbixAgent:
  image:
    repository: gcr.io/bitninjaio/zabbix
    tag: 5.4-agent
    pullPolicy: "Always" # "IfNotPresent"
    pullSecrets: [ "name": "bitninjaio-at-gmail-dot-com" ]
  ZBX_HOSTNAME: zabbix-server
  ZBX_SERVER_HOST: 127.0.0.1
  ZBX_SERVER_PORT: 10051
  ZBX_PASSIVESERVERS: 127.0.0.1
  ZBX_ACTIVE_ALLOW: false
