apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: zabbix-web
    app.kubernetes.io/name: zabbix-web
  name: zabbix-web
spec:
  replicas: {{ .Values.zabbixWeb.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: zabbix-web
      app.kubernetes.io/name: zabbix-web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: zabbix-web
        app.kubernetes.io/name: zabbix-web
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                - zabbix-web
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: zabbix-web
        image: {{ .Values.zabbixWeb.image.repository }}:{{ .Values.zabbixWeb.image.tag }}
        imagePullPolicy: {{ .Values.zabbixWeb.image.pullPolicy }}
        ports:
        - name: zabbix-web
          containerPort: 8080
          protocol: TCP
        env:
        - name: ZBX_SERVER_HOST
          value: {{ .Values.zabbixWeb.ZBX_SERVER_HOST | quote }}
        - name: ZBX_SERVER_PORT
          value: {{ .Values.zabbixWeb.ZBX_SERVER_PORT | quote }}
        - name: ZBX_SERVER_NAME
          value: {{ .Values.zabbixWeb.ZBX_SERVER_NAME | quote }}
        - name: DB_SERVER_HOST
          value: {{ .Values.zabbixWeb.DB_SERVER_HOST | quote }}
        - name: DB_SERVER_PORT
          value: {{ .Values.zabbixWeb.DB_SERVER_PORT | quote }}
        - name: POSTGRES_USER
          value: {{ .Values.zabbixWeb.POSTGRES_USER | quote }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.zabbixWeb.POSTGRES_PASSWORD | quote }}
        - name: POSTGRES_DB
          value: {{ .Values.zabbixWeb.POSTGRES_DB | quote }}
        lifecycle:
          preStop:
            exec:
              command: [ "/bin/sh", "-c", "pkill apache" ]
{{- if .Values.zabbixWeb.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.zabbixWeb.image.pullSecrets | indent 8 }}
{{- end }}
