apiVersion: v1
kind: Service
metadata:
  name: zabbix-postgresql
  labels:
    app.kubernetes.io/name: zabbix-postgresql
    app.kubernetes.io/component: zabbix-postgresql
spec:
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: zabbix-postgresql
  selector:
    app.kubernetes.io/name: zabbix-postgresql
    app.kubernetes.io/component: zabbix-postgresql
