apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
  labels:
    app.kubernetes.io/name: zabbix-server
    app.kubernetes.io/component: zabbix-server
spec:
  ports:
  - port: 10051
    targetPort: 10051
    protocol: TCP
    name: zabbix-trapper
  - port: 10052
    targetPort: 10052
    protocol: TCP
    name: zabbix-jmx
  selector:
    app.kubernetes.io/name: zabbix-server
    app.kubernetes.io/component: zabbix-server
